movies_rdd=sc.textFile("../../Movielens/movies.dat")
genre=movies_rdd.map(lines=>lines.split("::")(2))
flat_genre=genre.flatMap(lines=>lines.split("\\|"))
genre_kv=flat_genre.map(k=>(k,1))
genre_count=genre_kv.reduceByKey((k,v)=>(k+v))
genre_sort= genre_count.sortByKey()
genre_sort.saveAsTextFile("result-csv")
System.exit(0)
